# Generated by Django 6.0.2 on 2026-05-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_proposal_proposed_deadline_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('expert', 'Expert')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='skills_required',
            field=models.TextField(blank=True, default=''),
        ),
    ]
