# Generated by Django 4.2.30 on 2026-05-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_bio_profile_hourly_rate_profile_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
